services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data

    # In docker-compose.yml
  web:
    build:
      context: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    working_dir: /code
    # The 'volumes' line is now gone
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend


  jenkins:
    build:
      context: .
      dockerfile: jenkins.Dockerfile
    user: root
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
        - ./jenkins_home:/var/jenkins_home
        - /var/run/docker.sock:/var/run/docker.sock
volumes:
  pgdata:
  jenkins_home: