# Generated by Django 5.2.8 on 2025-12-03 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_location_unique_location'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='location',
            name='unique_location',
        ),
        migrations.AddConstraint(
            model_name='location',
            constraint=models.UniqueConstraint(fields=('city', 'state', 'location_type'), name='unique_location'),
        ),
    ]
