# Generated by Django 5.2.2 on 2025-06-06 22:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_date', models.DateTimeField(verbose_name='date applied')),
                ('benefits', models.TextField(blank=True)),
                ('description', models.TextField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('pay', models.CharField(blank=True, max_length=100)),
                ('position_title', models.CharField(max_length=200)),
                ('requirements', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('applied', 'Applied'), ('interviewing', 'Interviewing'), ('offered', 'Offered'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn'), ('accepted', 'Accepted'), ('archived', 'Archived')], default='applied', max_length=20)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.company')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.location')),
            ],
        ),
    ]
