# Generated by Django 5.2.8 on 2025-12-08 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0005_alter_application_options_application_posting_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('applied', 'Applied'), ('interviewing', 'Interviewing'), ('offered', 'Offered'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn'), ('accepted', 'Accepted'), ('archived', 'Archived')], default='applied', max_length=20),
        ),
    ]
