# Generated by Django 5.2.3 on 2025-06-18 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='headquarters_location',
        ),
    ]
